apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zookeeper/base
  - nifi/base

images:
  - name: apache/nifi
    newName: apache/nifi
    newTag: 2.7.0
  - name: placeholder/zookeeper
    newName: zookeeper
    newTag: 3.9.1

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: nifi
    spec:
      replicas: 3
