apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nifi

resources:
   - cluster-svc.yaml
   - internal-svc.yaml
   - pvc.yaml
   - zookeeper-deploy.yaml
   - nifi-deploy.yaml




