apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nifi

resources:
   - nifi-auth.yaml
   - nifi-pvc.yaml
#   - nifi-conf-pvc.yaml
   - zookeeper.yaml
   - nifi-deployment.yaml
   - configmap-ssl.yml




