apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nifi

resources:
   - nifi-deployment.yaml

#secretGenerator:
#  - name: nifi-tls
#    files:
#      - keystore.jks
#      - truststore.jks
#    type: Opaque

