apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nifi

resources:
   - namespace.yaml
   - nifi-auth.yaml
#   - nifi-pvc.yaml
   - zookeeper.yaml
   - nifi-deployment2-working.yaml
   - configmap-ssl.yml




